export const ADD_PROBLEM = "ADD_PROBLEM";
export const ADD_EXISTING_ALTERNATIVE = "ADD_EXISTING_ALTERNATIVE";
export const ADD_SOLUTION = "ADD_SOLUTION";
export const ADD_KEY_METRICS = "ADD_KEY_METRICS";
export const ADD_UNIQUE_VALUE_PROPOSITION = "ADD_UNIQUE_VALUE_PROPOSITION";
export const ADD_HIGH_LEVEL_CONCEPT = "ADD_HIGH_LEVEL_CONCEPT";
export const ADD_UNFAIR_ADVANTAGE = "ADD_UNFAIR_ADVANTAGE";
export const ADD_CHANNELS = "ADD_CHANNELS";
export const ADD_CUSTOMER_SEGMENTS = "ADD_CUSTOMER_SEGMENTS";
export const ADD_EARLY_ADOPTERS = "ADD_EARLY_ADOPTERS";
export const ADD_COST_STRUCTURE = "ADD_COST_STRUCTURE";
export const ADD_REVENUE_STREAMS = "ADD_REVENUE_STREAMS";

export const EDIT_PROBLEM = "EDIT_PROBLEM";
export const EDIT_EXISTING_ALTERNATIVE = "EDIT_EXISTING_ALTERNATIVE";
export const EDIT_SOLUTION = "EDIT_SOLUTION";
export const EDIT_KEY_METRICS = "EDIT_KEY_METRICS";
export const EDIT_UNIQUE_VALUE_PROPOSITION = "EDIT_UNIQUE_VALUE_PROPOSITION";
export const EDIT_HIGH_LEVEL_CONCEPT = "EDIT_HIGH_LEVEL_CONCEPT";
export const EDIT_UNFAIR_ADVANTAGE = "EDIT_UNFAIR_ADVANTAGE";
export const EDIT_CHANNELS = "EDIT_CHANNELS";
export const EDIT_CUSTOMER_SEGMENTS = "EDIT_CUSTOMER_SEGMENTS";
export const EDIT_EARLY_ADOPTERS = "EDIT_EARLY_ADOPTERS";
export const EDIT_COST_STRUCTURE = "EDIT_COST_STRUCTURE";
export const EDIT_REVENUE_STREAMS = "EDIT_REVENUE_STREAMS";

export const DELETE_PROBLEM = "DELETE_PROBLEM";
export const DELETE_EXISTING_ALTERNATIVE = "DELETE_EXISTING_ALTERNATIVE";
export const DELETE_SOLUTION = "DELETE_SOLUTION";
export const DELETE_KEY_METRICS = "DELETE_KEY_METRICS";
export const DELETE_UNIQUE_VALUE_PROPOSITION =
  "DELETE_UNIQUE_VALUE_PROPOSITION";
export const DELETE_HIGH_LEVEL_CONCEPT = "DELETE_HIGH_LEVEL_CONCEPT";
export const DELETE_UNFAIR_ADVANTAGE = "DELETE_UNFAIR_ADVANTAGE";
export const DELETE_CHANNELS = "DELETE_CHANNELS";
export const DELETE_CUSTOMER_SEGMENTS = "DELETE_CUSTOMER_SEGMENTS";
export const DELETE_EARLY_ADOPTERS = "DELETE_EARLY_ADOPTERS";
export const DELETE_COST_STRUCTURE = "DELETE_COST_STRUCTURE";
export const DELETE_REVENUE_STREAMS = "DELETE_REVENUE_STREAMS";

export const REORDER_PROBLEM = "REORDER_PROBLEM";
export const REORDER_EXISTING_ALTERNATIVE = "REORDER_EXISTING_ALTERNATIVE";
export const REORDER_SOLUTION = "REORDER_SOLUTION";
export const REORDER_KEY_METRICS = "REORDER_KEY_METRICS";
export const REORDER_UNIQUE_VALUE_PROPOSITION =
  "REORDER_UNIQUE_VALUE_PROPOSITION";
export const REORDER_HIGH_LEVEL_CONCEPT = "REORDER_HIGH_LEVEL_CONCEPT";
export const REORDER_UNFAIR_ADVANTAGE = "REORDER_UNFAIR_ADVANTAGE";
export const REORDER_CHANNELS = "REORDER_CHANNELS";
export const REORDER_CUSTOMER_SEGMENTS = "REORDER_CUSTOMER_SEGMENTS";
export const REORDER_EARLY_ADOPTERS = "REORDER_EARLY_ADOPTERS";
export const REORDER_COST_STRUCTURE = "REORDER_COST_STRUCTURE";
export const REORDER_REVENUE_STREAMS = "REORDER_REVENUE_STREAMS";
